### ISSUE TITLE
Error building on Master branch

### ISSUE THREAD

**Issue by waleedhammam** [couchbase/forestdb#21]
I did the following steps on ubuntu 18.04 
```
mkdir build
cd build
cmake ../
make all
```
it produces an error:
```
/forestdb/utils/debug.cc:88:5: error: ‘ucontext’ was not declared in this scope
     ucontext *u = (ucontext *)context;
     ^~~~~~~~
```
![Screenshot from 2019-05-23 13-31-43](https://user-images.githubusercontent.com/10658229/58249496-5997da80-7d5f-11e9-875c-a0e5743570dd.png)

**Comment by hisundar** [comment]
Looks like you are missing kernel source headers for your OS
Could you perhaps try
`sudo apt-get install linux-headers-$(uname -r)`
and update if the build issue goes away?

**Comment by waleedhammam** [comment]
No it didn't work. but it tried with tag v1.2 and worked well
